darold/pgbadger

README
Used pgbadger a long time ago, and was hoping to use it again. found some typos and figured that I'd try to help by contributing the updates
=> Small typographical corrections

doc/pgBadger.pod
=> Fix typo in 'queries'

pgbadger
Postgres sometimes generate broken CSV, I use this patch for correct process it. This patch only 8 new lines of code, but for correct indentation I reindent many others...
=> Try continue CSV parsing after broken CSV line

Makefile.PL
Here is the patch for issue #237
Thanks
=> Makefile.PL: changed manpage section from '1' to '1p', fixes #237

index.html
...log analyzer ~~build~~ built for speed...
=> Typo on public site: build > built

resources/LICENSE
I'll need that information for the debian/copyright file, and as it might be interesting for others as well, I'm submitting it for inclusion upstream.
=> Add LICENSE file noting the licenses used by the resource files

pgbadger
fix a spelling error and add open left paren to the stop for regex_prefix_dbclient
=> fix a spelling error and add open left paren to the stop for regex_prefix_dbclient

README, pgbadger
Damien Clochard is the best guy in the whole world... but I think he is just over-matched in logo creation by Damien Cazeils !!
...
and I don't like French  ;-)
=> logo is from Damien Cazeils (and english in comments is better)

README, doc/pgBadger.pod
Minor fix to remove repeated "Perl script" from README and doc.
=> Fix repeated info in README and doc.

pgbadger
Avoid losing time with stupid mistakes
=> Sanity check to avoid end time before start time

pgbadger
Closes: #367 
@dtseiler Can you test this ?
=> Use an isolated tmpdir

CONTRIBUTING.md, Makefile.PL
=> Ease contribution to documentation

t/consistency.t
Checks if plain mode and binary mode provide the same result
=> [ci] Add consistency tests

.gitignore, pgbadger
=> Job per file long option not parsed

Dockerfile, README, doc/pgBadger.pod
Base on comment in https://github.com/dalibo/pgbadger/pull/388
=> Feat docker

Dockerfile, README, doc/pgBadger.pod
=> Docker: automated build & updates

pgbadger
=> Delete current temp file info if we meet an error for the same PID

pgbadger
=> Apply timezone offset to bar charts

README, doc/pgBadger.pod
=> Add doc warning about log_MDS vs log_D + log_S

pgbadger
=> Fix broken grid when no temp files activity

pgbadger
Here's what we have right now.
```html
<div class="tab-pane active" id="histogram-session-times-graph">                                                
<tr><td colspan="3"><div class="jqplot-graph"><blockquote><b>NO DATASET</b></blockquote></div></td></tr>
</div>                                                                                                          
```
=> Fix some invalid HTML issues

README
First attempt at a pull request! After reviewing previous PR #504 added some very minor spelling and grammar fixes to the readme file.
=> Minor readme edit

README, README.md, doc/pgBadger.pod
The changes bring improvements to the README and are intended to
rephrase/reword some parts while leaving the meaning unchanged.
The changes in this PR are to `doc/pgBadger.pod`, the other changes were generated
by running `make README` as mentioned in [CONTRIBUTING.md](https://github.com/darold/pgbadger/blob/master/CONTRIBUTING.md#keep-documentation-updated)
=> Fixes #325 - docs improvements

pgbadger
Some was done by a previous PR, but these two are missing
=> Add 'g' option to replace all bind parameters

pgbadger
=> Fix text-based error/events reporting

README, README.md, doc/pgBadger.pod, pgbadger
Previous round of edits was good but missed a few spots.
=> Typo fixes

pgbadger
1. fixed typo in "Sessions per application";
2. fixed "INSERT/UPDATE/DELETE Traffic" chart bug.
=> fixed typo and chart bug
