darold/pgbadger

- pgbadger
When using the "! =" in queries a random bug appears.
This error is due to order of items in "% SYMBOLS" hashtable is  random.
A quick fix is sorting %SYMBOLS  :) : != is before =.
How to reproduce:
Use the following log file:
Feb 10 14:55:24 postgres postgres[23121]: [135-1] [23121]: [125-1] user=bugfix,db=bugfix,app=[unknown],client=10.1.1.1 LOG:  duration: 0.080 ms  execute <unnamed>: SELECT * FROM SOMEBASE WHERE BUG='DEMO' AND TYPE!='DEMO'
Run : pgbadger -f syslog sample.log
In generated report you can see : 
SELECT * FROM SOMEBASE WHERE BUG = 'DEMO' AND TYPE $$PGBGYA$$!=$$PGBGYB$$ 'DEMO'; 
In HTML source : 
`
<i class="icon-copy" title="Click to select query"></i>
<span class="kw1">SELECT</span>
<span class="sy0">*</span>
<span class="kw1">FROM</span>
SOMEBASE
<span …
> Sort %SYMBOLS hashtable to remove "!=" / "=" bug.

- pgbadger
- tools/pgbadger_tools
This patch allow more precise query type statistics.
SELECT and COPY TO have distinct counters (relevant fields are renamed to Read instead of SELECT), same for WRITE and COPY FROM.
CTE queries have their own categories.
DDL and TCL are regrouped in two new categories.
I tried to update all relevant code to take this into account, but it's very likely that I forgot some :(
I didn't change the graphs, since they explicitely specify SELECT / UPDATE and so on. A new graph for CTE queries might be interesting though.
Left me know if I need to do some more work on this.
> Handle more kind or query types.

- index.html
Debian unstable and apt.postgresql.org have up-to-date pgBadger packages
now.
> Add link to apt.postgresql.org and fix a typo in the yum section

- pgbadger
This pull request is for Issue # 277.
Linux use 10 as SIGUSR1 and 12 as SIGUSR2.
But another OSs use other numbers, for example signal 10 is SIGBUS and signal 12 is SIGSYS in BSD/OSX/Solaris.
> We should use the mnemonic rather than a signal number.

- pgbadger
When passing log content to pgbadger via stdin, it is at the moment unable to read the data.
How to reproduce:
```
cat logfile | pgbadger -O /somewhere/output -
```
Creates the same output disregarding file content of logfile (even when logfile is empty).
This hotfix disables pgbouncer logfile format detection and enables pgbadger to process the data from stdin once again. Reading files in pgbouncer format from stdin would probably need an extra command-line option.
> Fix reading from stdin by disabling pgbouncer file format detection

- pgbadger
During the execution of pgbadger lines like this are not autodetected as csv:
2016-08-18 08:31:00.365 GMT+3,"user_project","devdb",16576,"172.17.43.32:59633",57b59c74.40c0,2,"",2016-08-18 08:31:00 GMT+3,,0,FATAL,57P03,"the database system is shutting down",,,,,,,,,""
> Detect timezones like GMT+3 on CSV logs

- pgbadger
- fix autovacuum statistic (empty graph) : parsing regex add tabulation 'optional' 
- fix some labels in vacuum graph caption.
The information on stats, tuples and pages was empty. After investigation it seems that the tabulation is deleted before (towards line 2783, it is $ t_query which is used and this one has no more tabulation) ...
I also fix some labels in the autovacuum report.
> Fix autovacuum report

- pgbadger
my $last; 
without any further default value is 'undef'.. 
adding replacing with 
my $last=''; 
makes it then defined,
> https://github.com/dalibo/pgbadger/issues/353

- README
- pgbadger
Closes: #351 
This patch drops `-B` option from CLI parser, inline help and documentation as proposed in #351 
I don't find the actual code using `bar_graph`. Looks like it is already dropped. Please confirm this !
cc @darold @jpargudo
> Drop --bar-graph option

- .editorconfig
- CONTRIBUTING.md
Reading pgBadger I found a lot of mixed tabs and spaces, trailing spaces, etc. Here is a `.editorconfig` to help keeping spacing sane.
> Add editorconfig configuration

- README
- doc/pgBadger.pod
- pgbadger
See #367 
`--pid-file` looks more regular when looking at other sotfwares. Also, it avoid managing a directory. I'm not fan of creating an inexistant directory. This will swallow typo in directory name. It's less intrusive to let customize pidfile.
Also, this deduplicate the `/pgbadger.pid` concatenation everywhere !
> Add --pid-file CLI switch

- README
- doc/pgBadger.pod
- pgbadger
"stderr" is not a default for -f , as when autodetection fails, there is no fallback to stderr
We had the problem with a customer whose log was too small. Adding -f stderr explicitely solved the problem.
I've discussed this with Gilles: he did change the behaviour. pgbadger needs 10 lines  (see line 13879).
> doc update : stderr is not a default for -f

- pgbadger
PostgreSQL 10 renamed 'transaction log' to 'WAL'.
> Fix checkpoint regex to match PostgreSQL 10 log messages.

- README
- doc/pgBadger.pod
- pgbadger
Some of the usage examples used appname= in the prefix, but the code
didn't recognize that token. Use app= in all examples, and add appname=
to the prefix parser.
> Consistently use app= in examples, and support appname=

- README
- doc/pgBadger.pod
- pgbadger
This patch intends to fix timezone issues (#352 #346) by applying TZ offset at parsing time.
So far, no regression seen with multi process, incremental mode, pgbouncer logs, syslog, csvlog and stderr logs.
> Apply timezone offset at parsing time

- pgbadger
> g modifier usage when unescaping log_line_prefix

- Makefile.PL
I'm updating Homebrew to support 10.0 but the current version of the makefile does not support OSX builds as `sed` does not support the bare `-i` in OSX.
> Fixes SED use for OSX builds

- README
- doc/pgBadger.pod
- pgbadger
pgbadger, doc/pgBadger.pod, and README were out of sync. Fix by running
"make", and slight editing of pgbadger when the pod file was more
correct.
Also, the input was using "\" line-continuations which would need to be
\\ for pod to correctly handle them. Fix by formatting as a single line
instead, which is better suitable for cut-and-paste (and there's already
longer lines in the surrounding text). In plus, crontabs do not support \
anyway. In passing, fix +%F crontab example to be +\%F because % is
magic in crontabs.
> Sync pgbadger, pod, and README, and fix some syntax errors

- t/02_basics.t
The syslog test checks if the result is exactly 24281 bytes, but if the
run takes 10s or more, the result is longer.
Generated on Tue Feb 19 12:24:58 2019
Log file: t/fixtures/pg-syslog.1.bz2
Parsed 59,921 log entries in **19s**  <-- PROBLEM HERE
Log start from 2019-02-11 13:15:39 to 2019-02-11 13:16:26
> t/02_basics.t: Don't fail if syslog test takes more than 10s

- pgbadger
When specifying a directory instead of a remote file, the program aborts
with a message like:
% pgbadger  ssh://postgres@pghost//postgres/data/log/
FATAL: can't get size of remote file,
please check what's going wrong with command:
ssh postgres@pghost "ls -l postgresql-Fri.log"
The problem is that the set_file_list function does not include the path
on the remote host, managing each file path as relative. Therefore
now there is an addition of $dirs before pushing the path to the @lfiles array.
However, this is due only when there is a directory, that is when the number
of remote files on each function invocation is not equal at one.
> Fix remote paths when using SSH.

- README
A little rewording here and there.
I was also thinking about removing all `perl` in front of `pgbadger` in order to gain some columns:
`perl pgbadger /var/log/foo`
will become
`pgbadger /var/log/foo`
> Fix readme

- README
- pgbadger
Remove `perl` in front of `pgbadger` within documentation.
See comment <https://github.com/darold/pgbadger/pull/504#issuecomment-500051470>
> Remove perl from documentation

- pgbadger
This is related to PR #501 and comment
<https://github.com/darold/pgbadger/pull/501#issuecomment-500052105>.
I don't like it too much, since `$prefix_vars{'t_timestamp'}` is scattered in a few places and therefore building `t_time` is too.
> Use a `$prefix_vars{'t_time'} to store the log time.

- README
- doc/pgBadger.pod
- pgbadger
again - was accidentially broken by bf2cb1e / forgotten in d9602a6 and d06af8b
> Fix URI samples in documentation

- pgbadger
835231a / PR #500 did break again the use of wildcards in SSH URI filenames that 0a45659 / #477 took care of. This patch should finally offer a solution that can deal with absolute and relative paths, spaces in paths, wildcards in filenames, single files and whole directories within the URI.
> fix SSH URIs for files, directories and wildcards

- README
Installation instructions currently indicate 7.x as the current version, while 11.x is the current release.
> Update README to reference 11.x instead of 7.x

- README
- README.md
- doc/pgBadger.pod
- pgbadger
Hi Gilles,
lz4 and zstd can offer a good compromise between speed and compression ratio. This PR add lz4 and zst compatibility. I hope everything is fine.
Note, maybe we should revise the `XZ_FACTOR`
Regards,
> Handle zstd and lz4

- README.md
There were three dates in the examples that used "2919" instead of "2019", so I've fixed those.
> Fix 2919 date typo

- pgbadger
Hello Gilles,
Sometimes it is not possible to detect uncompressed file size. I suggest to fall back to default compressed size multiplied by `$XZ_FACTOR`.
Here is my use case, we compress postgres logs by sending log to stdin (look `<`):
```
zstd --compress --stdout < /var/log/postgresql/postgresql-10-main.log > pg.log.zst
```
(We do like this because zstd do not like to compress a modified file during compression. see there for the complete explanation https://github.com/facebook/zstd/issues/1926#issuecomment-564170480)
Here is a debug output of pgbadger : 
```
DEBUG: timezone not specified, using 0 seconds
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Looking for file size using command: zstd -v -l pg.log.zst |grep Decompressed | awk  -F"[ (]*" '{print $5}'
*** zstd …
```
> Fall back to default fle size when totalsize could not be determined

- pgbadger
https://github.com/darold/pgbadger/commit/ec85319e119bce8e86c885debb2f863aaa9c57e3 introduced  a new command line option `--noexplain` but in the source the option is actually spelled like `--no-explain`
> fixes the commandline parameter from --no-explain to --noexplain

- doc/pgBadger.pod
Simple mismatch in docs vs code
> Typo in parameter for html directory output

- pgbadger
For one query if there are multiple same bind parameters, it could be interesting to replace all of them.
It's very usefull to replay  slow queries for example . 
For example with this log : 
~~~
2021-04-19 06:20:26 CEST [133854]: [1-1] db=test,user=user1 LOG:  duration: 346.806 ms  execute 7048305f4c4ba9537a8ae75d60c84457: SELECT
t1."id" as "id", t1."o_id" as "o_id"
FROM
table1 t1
WHERE t1."o_id" = $1
AND t1."p_id" = $2
UNION ALL
SELECT
t2."id" as "id", t2."o_id" as "o_id"
FROM
table2 t2
WHERE t2."o_id" = $1
AND t2."p_id" = $2
2021-04-19 06:20:26 CEST [133854]: [2-1] db=test,user=user1 DETAIL:  parameters: $1 = 'xxxxxxx-a92a-4dc4-yyyy-e74892d4906f', $2 = 'xxxxxxx-9cc5-456d-yyyy-b7032123b7b2'
~~~
With the current version with this command : pgbadger -f  --no-prettify --nocomment …
> Add 'g' option to replace all bind parameters not only the first found

- pgbadger
- t/03_consistency.t
- t/fixtures/pg-timezones.log
In the function change_timezone, localtime was used on a time returned
by timegm_nocheck.
In [1] [2] it's mentioned that timegm_nocheck is the inverse of gmtime and
timelocal_nocheck the inverse of localtime.
This commit also adds a regression test.
[1] https://man7.org/linux/man-pages/man3/timegm.3.html
[2] https://perldoc.perl.org/Time::Local
> Fixes #662 related to timezone calculations

- pgbadger
It's a pretty simple tweak to the regex(es) for syslog / syslog2. So far as I can tell in testing this doesn't break any existing parsing/processing, though obviously with another optional (uncaptured) group there's always the potential for an impact on parsing performance, even though I haven't seen any perceptible change in performance with the change when parsing log files I've modified specifically to match the currently expected syslog format.
Intended to address issue #681.
> Syslog format: Allow session line to be 1 int vs 2 ints split by dash

- t/04_advanced.t
Syslog timestamps do not contain the year, so what used to get
interpreted as February 2021 is now February 2022. Fix by using
wildcards in the grep command.
Close #715.
> t/04_advanced.t: Fix syslog test

- doc/pgBadger.pod
We don't generate an error report, so filename should not contain `_report`.
> doc: fix filename for incremental every week command

- doc/pgBadger.pod
I think this is a typo as the description states August 2019.
> fix typo: 2919 to 2019

- pgbadger
Hi @darold 
[FIX for Issue](https://github.com/darold/pgbadger/commit/a52a22d3640baaba915e0b5e0f0414821957f282) https://github.com/darold/pgbadger/issues/776
#776 
Starting from commit [a1bb778](https://github.com/darold/pgbadger/commit/a1bb77814225118f9772317e681b0dc6c3919aec) I have modified the cleanup code so that it works well on outdir and html-outdir AND it is simplified AND it works for monthly reports.
The logic I applied is similar to the one before
EXCEPT for the case where there is NO 'noclean' and NO 'retention' flags specified.
In this case, the current code was doing BIN cleanup for the previous month and older, even if it was run on the 1st of the month.
I have put in place a more coherent strategy (as far as I believe it is):
do BIN cleanup by simulating a retention …
> FIX for Issue #776

- pgbadger
Yes, it is in the doc on the website, but in the `--help` it would have spared me some time. I didn't know that %p was compulsory, as most customers do keep it - not all of them.
> --help: %p/%t must be there

- pgbadger
Hello, @darold 👋🏽 
I noticed that despite `pgbouncer` supporting the reporting of `wait_time` since the [`1.8.0`](https://www.pgbouncer.org/changelog.html#pgbouncer-18x) release, that this is not yet supported by `pgbadger`. So, I took some inspiration from how the computations for the average duration of queries was done to achieve the same thing.
This is the relevant output of running `pgbadger t/fixtures/pgbouncer.log.gz`, which seems correct, taking the values (listed below) into account:
```
zcat -f t/fixtures/pgbouncer.log.gz | grep "wait time" 
2018-09-12 16:09:54.778 3394 LOG stats: 281 xacts/s, 1967 queries/s, in 118855 B/s, out 93433 B/s, xact 17057 us, query 2360 us, wait time 8672 us
2018-09-12 16:10:54.781 3394 LOG stats: 481 xacts/s, 481 queries/s, in 29782 B/s, out 103650 …
```
> Add suport for `pgbouncer`'s average waiting time

- ChangeLog
- README
- README.md
- doc/pgBadger.pod
- pgbadger
Hello again, @darold !
While I was working on #788, I noticed this small incongruency between the plot name and the title on the upper left corner, so I thought I'd suggesta a fix for it too.
Also, I believe that there was some drift as to updating the docs from #781 so I did that too.
> Nit-fix: `Queries Average duration` -> `Average Query Duration`

- pgbadger
Hello 👋🏽 
I thought this would be an interesting feature to add as one can have a decent average autovacuum duration, but some of them might be running too long and one wouldn't know it.
While trying to implement this feature, I stumbled upon the fact that the parsing for `autovacuum`'s `system usage: CPU: user: ...` line is broken. I hadn't noticed it thus far, but have checked a report I generated a couple of days ago and it's also missing the longest vacuum duration:
So, I fixed that, and begun implementing the chart.
To test my implementation, I generated a report from the following output:
<details><summary>Details</summary>
<p>
```sql
Feb 10 23:06:30 test-pc postgres[10808]: [1-1] db=,user=,app=,client= LOG:  automatic vacuum of table "db.public.tablename": index scans: 1
pages: 0 …
```
> Add support for `{max,avg,min} autovacuum duration` & fix `autovacuum`'s `system usage: CPU: ...` line parsing

- pgbadger
Fixing the use of uninitialized value in pattern match (m//) at /usr/bin/pgbadger line 21645
> Fix use of uninitialized value in pattern match
